### ISSUE TITLE
Question around using different Slack channels per-page

### ISSUE THREAD

**Issue by eddgrant** [alphagov/tech-docs-monitor#32]
Hey folks,

From reading the [Slack Webhooks documentation](https://api.slack.com/messaging/webhooks) it seems that Slack webhooks are only able to post to a single pre-configured Slack channel. I notice that the configuration here only configures a single Slack URL environment variable, yet different pages might have different `OWNER_SLACK` frontmatter variables. Does this mean that in practice only a single Slack channel can be used for all notifications?

Many thanks,

Edd

**Comment by lfdebrux** [comment]
Hi @eddgrant,

That's correct, [new Slack apps](https://api.slack.com/authentication/quickstart) can only post to one channel, this app was set up when (old) [incoming webhooks](https://api.slack.com/legacy/custom-integrations/messaging/webhooks) could post to any channel.

I'm going to do some work to try and support new Slack apps however, so hopefully this should be fixed soon.
